name: Validate genesis.json
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'dydx-mainnet-1/genesis.json'
  push:
    paths:
      - 'dydx-mainnet-1/genesis.json'
    branches:
      - main
      - master

jobs:
  dydx-mainnet-1:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Validate final genesis file
        run: make validate-dydx-mainnet-1-final-genesis
